services:
  ishtech-springboot-multidb-app-postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_TO_USE: postgres
        SERVER_PORT: ${SERVER_PORT:-8080}
        APP_VERSION:
    image: ishtech-springboot-multidb-app:postgres${APP_VERSION:+"-"$APP_VERSION}
    container_name: ishtech_springboot_multidb_app_postgres
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      ishtech-springboot-multidb-db-postgres:
        condition: service_healthy

  ishtech-springboot-multidb-db-postgres:
    image: postgres:18
    container_name: ishtech_springboot_multidb_db_postgres
    environment:
      - POSTGRES_DB=multidb
      - POSTGRES_USER=multidbuser
      - POSTGRES_PASSWORD=multidbpass
    ports:
      - "${DB_PORT:-15432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      start_period: 45s
