services:
  ishtech-springboot-multidb-app-mysql:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_TO_USE: mysql
        SERVER_PORT: ${SERVER_PORT:-8080}
        APP_VERSION:
    image: ishtech-springboot-multidb-app:mysql${APP_VERSION:+"-"$APP_VERSION}
    container_name: ishtech_springboot_multidb_app_mysql
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      ishtech-springboot-multidb-db-mysql:
        condition: service_healthy

  ishtech-springboot-multidb-db-mysql:
    image: mysql:8.4
    container_name: ishtech_springboot_multidb_db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Qwer4321
      - MYSQL_DATABASE=multidb
      - MYSQL_USER=multidbuser
      - MYSQL_PASSWORD=multidbpass
    ports:
      - "${DB_PORT:-13306}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      start_period: 45s
