spring:
  application:
    name: springboot-multi-db-mariadb
  datasource:
    name: multidb-mariadb-ds
    url: jdbc:mariadb://localhost:23306/multidb
    username: multidbuser
    password: multidbpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
